
spring:
  jackson.deserialization.fail-on-unknown-properties: false
  groovy.template.check-template-location: false
  stubrunner.use-microservice-definitions: true
  stubrunner.skip-local-repo: true

rest.api.version: 1.0
city.finding.service.url: "http://api.openweathermap.org/data/2.5/weather"

graphite:
  host: graphite.hackathon.dev.4finance.net

metrics.path:
  country: cz
  app: loan-application-service-cz

stubrunner.stubs:
  repository.root: "http://nexus.hackathon.dev.4finance.net/nexus/content/repositories/releases/"
  group: com.ofg
  module: stub-definitions

server:
  port: 9054
